### ISSUE TITLE
Docker and Virtualization chapter or section?

### ISSUE THREAD

**Issue by docquantum** [VegaDeftwing/OpGuidesHugoSrc#2]
Oi, I know a thing or two about docker and how you can use it to run services and create static dev environments. I can bestow a bit of knowledge if wanted.

**Comment by VegaDeftwing** [comment]
That'd be awesome! There's a spot for containerization in Chapter 19: Servers, though It may be deserving of it's own section, since I rearranged Chapter 24 is open, it could go there?
